// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDir10vy0pTGM9eL3GN3RvYYgWIBBoLOSQ',
    appId: '1:703800474542:web:6bcadbf8accca1d9d6663f',
    messagingSenderId: '703800474542',
    projectId: 'lec-recorder',
    authDomain: 'lec-recorder.firebaseapp.com',
    storageBucket: 'lec-recorder.appspot.com',
    measurementId: 'G-F7SYJB0FCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp1CkkfS_HBTTI9CdsMaMOnF_Ttr7PtB4',
    appId: '1:703800474542:android:4a4863567caf94d6d6663f',
    messagingSenderId: '703800474542',
    projectId: 'lec-recorder',
    storageBucket: 'lec-recorder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbdi1qOLtIJGg5A2HRQlKAEmjBR0IR43I',
    appId: '1:703800474542:ios:860d66d9b18b41e9d6663f',
    messagingSenderId: '703800474542',
    projectId: 'lec-recorder',
    storageBucket: 'lec-recorder.appspot.com',
    iosClientId: '703800474542-g5cb85bi9tafd95hiln60roa6erpo6gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.lecrecorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbdi1qOLtIJGg5A2HRQlKAEmjBR0IR43I',
    appId: '1:703800474542:ios:860d66d9b18b41e9d6663f',
    messagingSenderId: '703800474542',
    projectId: 'lec-recorder',
    storageBucket: 'lec-recorder.appspot.com',
    iosClientId: '703800474542-g5cb85bi9tafd95hiln60roa6erpo6gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.lecrecorder',
  );
}
